# Generated by Django 3.2 on 2023-06-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-date_of_create',), 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='flat',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='published',
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.CharField(default=1, max_length=128, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='phone',
            field=models.CharField(default=1, max_length=32, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=32, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_of_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата отправления'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Вопрос'),
        ),
    ]
