# Generated by Django 3.2 on 2023-06-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20230617_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='consideration',
            field=models.BooleanField(default=False),
        ),
    ]
