# Generated by Django 5.0.4 on 2024-05-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_comment_consideration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='consideration',
            field=models.BooleanField(default=False, verbose_name='Рассмотрена'),
        ),
    ]
