# Generated by Django 3.2 on 2023-06-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats_sale', '0002_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.PositiveIntegerField(default=1, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
