# Generated by Django 3.2 on 2023-06-10 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flats_sale', '0010_auto_20230609_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='object_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='o_category', to='flats_sale.object'),
        ),
    ]
