# Generated by Django 3.2 on 2023-06-10 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flats_sale', '0011_alter_category_object_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='object_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flats_sale.object', verbose_name='Объект'),
        ),
    ]
