# Generated by Django 3.2 on 2023-06-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats_sale', '0015_alter_category_object_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='object_name',
        ),
        migrations.AddField(
            model_name='object',
            name='category_name',
            field=models.ManyToManyField(to='flats_sale.Category'),
        ),
    ]
