# Generated by Django 3.2 on 2023-06-10 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flats_sale', '0016_auto_20230610_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='category_name',
        ),
        migrations.AddField(
            model_name='object',
            name='category_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flats_sale.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
