# Generated by Django 3.2 on 2023-06-16 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats_sale', '0018_auto_20230610_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='object_name',
            new_name='name',
        ),
    ]
