# Generated by Django 5.0.4 on 2024-05-07 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats_sale', '0020_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='apartment',
        ),
        migrations.AddField(
            model_name='category',
            name='floor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='flats_sale.floor', verbose_name='Этаж'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='floor',
            name='number',
            field=models.IntegerField(verbose_name='Номер этажа'),
        ),
    ]
