# Generated by Django 5.0.4 on 2024-05-08 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats_sale', '0021_remove_floor_apartment_category_floor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='floor',
        ),
        migrations.AddField(
            model_name='floor',
            name='apartment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flats_sale.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='floor',
            name='number',
            field=models.IntegerField(),
        ),
    ]
