# Generated by Django 5.0.4 on 2024-05-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats_sale', '0022_remove_category_floor_floor_apartment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='apartment',
        ),
        migrations.AddField(
            model_name='category',
            name='floors',
            field=models.ManyToManyField(to='flats_sale.floor'),
        ),
    ]
