# Generated by Django 5.0.4 on 2024-05-09 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats_sale', '0023_remove_floor_apartment_category_floors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='floors',
        ),
        migrations.AddField(
            model_name='category',
            name='floors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='flats_sale.floor'),
        ),
    ]
