# Generated by Django 5.0.4 on 2024-05-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats_sale', '0024_remove_category_floors_category_floors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='floors',
        ),
        migrations.AddField(
            model_name='category',
            name='floors',
            field=models.ManyToManyField(to='flats_sale.floor'),
        ),
    ]
