# Generated by Django 5.0.4 on 2024-05-19 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats_sale', '0025_remove_category_floors_category_floors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=128, verbose_name='Номер договора')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flats_sale.object', verbose_name='Название объекта')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
            },
        ),
    ]
